"""client processes links consent and videos"""

import sqlalchemy as sa
from alembic import op

revision = "768dceeb04b2"
down_revision = "0001_admin_auth"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_processes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("passport_number", sa.String(length=32), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_processes")),
    )
    op.create_index(
        op.f("ix_client_processes_status"), "client_processes", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_client_processes_updated_at"), "client_processes", ["updated_at"], unique=False
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_process_id", sa.Uuid(), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_process_id"],
            ["client_processes.id"],
            name=op.f("fk_consent_records_client_process_id_client_processes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
    )
    op.create_index(
        op.f("ix_consent_records_client_process_id"),
        "consent_records",
        ["client_process_id"],
        unique=False,
    )
    op.create_table(
        "registration_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_process_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_process_id"],
            ["client_processes.id"],
            name=op.f("fk_registration_links_client_process_id_client_processes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_registration_links_token_hash")),
    )
    op.create_index(
        op.f("ix_registration_links_client_process_id"),
        "registration_links",
        ["client_process_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registration_links_expires_at"), "registration_links", ["expires_at"], unique=False
    )
    op.create_table(
        "video_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_process_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=100), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_process_id"],
            ["client_processes.id"],
            name=op.f("fk_video_submissions_client_process_id_client_processes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_submissions")),
        sa.UniqueConstraint(
            "client_process_id", name=op.f("uq_video_submissions_client_process_id")
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_video_submissions_storage_key")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_submissions")
    op.drop_index(op.f("ix_registration_links_expires_at"), table_name="registration_links")
    op.drop_index(op.f("ix_registration_links_client_process_id"), table_name="registration_links")
    op.drop_table("registration_links")
    op.drop_index(op.f("ix_consent_records_client_process_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_client_processes_updated_at"), table_name="client_processes")
    op.drop_index(op.f("ix_client_processes_status"), table_name="client_processes")
    op.drop_table("client_processes")
    # ### end Alembic commands ###
